### ISSUE TITLE
dev 出错

### ISSUE THREAD

**Issue by cbq-sea** [wlc534/snowpack-react-antd#1]
Import "antd/es/button" could not be resolved.

**Comment by wlc534** [comment]
组件引入方式要统一下，import {Button, Table, Divider, Modal, Row, Col, Input, Select, Switch, DatePicker, message,Popconfirm,Spin,Icon,Form} from "antd"; 或者 import Select from 'antd/es/select';
import Collapse from 'antd/es/collapse';
import Tag from 'antd/es/tag';
import message from 'antd/es/message';  两个混用有问题
